- name: restart networking
  service:
    name: networking
    state: restarted
  when: network_booted.changed == false

- name: reload networking
  command: "/sbin/ifreload -a"
  when: network_booted.changed == false

#- name: restart ntp
#  service:
#    name: systemd-timesyncd
#    state: restarted
#  when: network_booted.changed == false

- name: restart chrony
  service:
    name: chrony
    state: restarted
  when: network_booted.changed == false

- name: new aliases
  command: newaliases

- name: restart postfix
  service:
    name: postfix
    state: restarted
  when: network_booted.changed == false
