- name: Delete olds pve-enterprise.list and pve-community.list
  file: 
    path: "/etc/apt/sources.list.d/{{ item }}"
    state: absent
  loop:
    - pve-enterprise.list
    - pve-community.list
    - ceph.list

- name: Copy Debian repositories
  copy:
    src: "files/pve{{ pve_version }}-sources.list"
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'

- name: Copy PVE repositories
  copy:
    src: "files/pve{{ pve_version }}-{{ license | default('enterprise') }}.list"
    dest: /etc/apt/sources.list.d/pve.list
    owner: root
    group: root
    mode: '0644'

- name: instalar common packages
  apt:
    name: "{{ common_packages}}"
    state: present
    update_cache: yes
    allow_unauthenticated: yes

- name: Actualiza todos los paquetes del proxmox
  apt:
    name: "*"
    state: latest
    update_cache: yes
  when: upgrade is defined

- name: Upgrade the OS (apt-get dist-upgrade)
  apt:
    update_cache: yes
    upgrade: dist
  when: upgrade is defined

